/**
 * Copyright 2026 FDU-AI-Agent-Camp
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from 'vitest'

import schemaSource from './generated/schema.d.ts?raw'

const REQUIRED_SCHEMAS = [
  'PaperStatusData',
  'PaperSummary',
  'PaperDetail',
  'FailedDuringStage',
  'PatrolResponse',
  'GraphResponse',
  'ErrorBody',
] as const

describe('generated/schema.d.ts artifact', () => {
  it('exists and is marked as openapi-typescript output', () => {
    expect(schemaSource).toContain('auto-generated by openapi-typescript')
    expect(schemaSource).toContain('export interface components')
    expect(schemaSource).toContain('export interface paths')
  })

  it('includes core V1 schema names from openapi.yaml', () => {
    for (const name of REQUIRED_SCHEMAS) {
      expect(schemaSource).toContain(`${name}:`)
    }
  })
})
