"""baseline papers and pipeline_runs

Revision ID: 17bad1e1a105
Revises: 
Create Date: 2026-07-12 20:37:50.865650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bad1e1a105'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('paradigm', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('graph_path', sa.String(length=500), nullable=True),
    sa.Column('head_path', sa.String(length=500), nullable=True),
    sa.Column('preview_available', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('graph_version', sa.String(length=20), nullable=False),
    sa.Column('extractor_config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('failed_during', sa.String(length=30), nullable=True),
    sa.Column('head_refine_warnings', sa.JSON(), nullable=False),
    sa.Column('classify_warnings', sa.JSON(), nullable=False),
    sa.Column('extract_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_runs')
    op.drop_table('papers')
    # ### end Alembic commands ###
