/** design-spec §11 + ui-design-progress §1.4.4 Patrol baseline copy. */
export const PATROL_BASELINE_COPY = {
  pageTitle: '共同体巡检',
  subtitle: '跨论文探测理论视角冲突与论点矛盾 · 需 2 篇 ready 论文',
  configTitle: '巡检配置',
  paperLabelA: '论文 A',
  paperLabelB: '论文 B',
  paperPlaceholder: '选择或输入 paper_id',
  runButton: '运行巡检',
  runButtonLoading: '分析中…',
  modeLensClashLabel: 'Lens Clash',
  modeLensClashCaption: '分析视角冲突 · 适用 HSS',
  modeContradictionLabel: 'Contradiction',
  modeContradictionCaption: '核心论点矛盾 · HSS/STEM',
  modeLabel: '巡检模式',
  hintSummary: '本地联调提示',
  hintBody: '在后端 seed demo 图谱后再运行巡检：',
  hintCommand: 'uv run python scripts/run_patrol.py --seed-demo-graphs',
  validationExactTwo: '请输入恰好 2 个 paper_id',
  validationDuplicate: (paperId: string) => `论文 A 与论文 B 不能选择同一篇论文（${paperId}）`,
  reportTitle: '巡检报告',
  graphNotReadyTitle: '图谱未就绪',
  graphNotReadyDescription: '所选论文尚未 ready，请先在文献库等待流水线完成。',
  graphNotReadyCta: '前往文献库',
  insufficientDataTitle: '数据不足',
  insufficientDataDescription: '换用 ready 状态的论文再试',
  insufficientDataCta: '换用论文',
  nodeRefGraphLink: '查看图谱',
} as const
